# Elegimos la imagen que queremos para el contenedor, en este acaso php 8.2
FROM php:8.2

# Instalamos las dependencias y librerías necesarias para trabajar con imágenes y gd
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    libjpeg-dev \
    libpng-dev \
    && docker-php-ext-configure gd --with-jpeg=/usr/include/ \
    && docker-php-ext-install gd

# Designamos la carpeta en la que vamos a poner el proyecto
WORKDIR /var/www/html

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copiamos el proyecto
COPY ImgAda .

# Damos los permisos necesarios
RUN chown -R www-data:www-data \
    /var/www/html/storage \
    /var/www/html/bootstrap/cache

# Instala el proyecto laravel
RUN composer install

# Servimos la api en el puerto 8000
CMD php artisan serve --host=0.0.0.0 --port=8000